import { AuthService } from '../auth/auth.services.js';
import { UserRepository } from '../user/user.repository.js';
import { CategoryRepository } from './category/category.repository.js';
import { CategoryService } from './category/category.service.js';
import { ProductRepository } from './product/product.repository.js';
import { ProductService } from './product/product.service.js';
import { VariantRepository } from './variant/variant.repository.js';
import { VariantService } from './variant/variant.service.js';
import { InventoryRepository } from './inventory/inventory.repository.js';
import { InventoryService } from './inventory/inventory.service.js';
import { StockMovementRepository } from './stock-movement/stock-movement.repository.js';
import { StockMovementService } from './stock-movement/stock-movement.service.js';
import { ProductMediaRepository } from './product-media/product-media.repository.js';
import { ProductMediaService } from './product-media/product-media.service.js';
import { CatalogService } from './catalog/catalog.service.js';
import { WishlistRepository } from './wishlist/wishlist.repository.js';
import { WishListService } from './wishlist/wishlist.service.js';
import { CartRepository } from './cart/cart.repository.js';
import { CartService } from './cart/cart.service.js';
const userRepo = new UserRepository();
const authService = new AuthService(userRepo);

const categoryRepo = new CategoryRepository();
const productRepo = new ProductRepository();
const variantRepo = new VariantRepository();
const inventoryRepo = new InventoryRepository();
const stockMovementRepo = new StockMovementRepository();
const productMediaRepo = new ProductMediaRepository();
const wishlistRepo = new WishlistRepository();
const cartRepo = new CartRepository();

export const categoryService = new CategoryService(categoryRepo, authService, userRepo);
export const productService = new ProductService(productRepo, categoryRepo, authService, userRepo, variantRepo);
export const stockMovementService = new StockMovementService(stockMovementRepo, inventoryRepo, authService, userRepo);
export const inventoryService = new InventoryService(inventoryRepo, variantRepo, authService, userRepo);
export const variantService = new VariantService(variantRepo, productRepo, inventoryRepo, stockMovementService, authService, userRepo);
export const productMediaService = new ProductMediaService(productMediaRepo, productRepo, variantRepo, authService, userRepo);
export const catalogService = new CatalogService(productRepo);
export const wishlistService = new WishListService(wishlistRepo);
export const cartService = new CartService(cartRepo, productRepo);
