-- AlterTable
ALTER TABLE `Payment` MODIFY `method` ENUM('BANK_TRANSFER', 'COD', 'E_WALLET', 'QRIS') NOT NULL,
    MODIFY `status` ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'EXPIRED') NOT NULL DEFAULT 'PENDING';
